### ISSUE TITLE
Sampling for the curves

### ISSUE THREAD

**Issue by yungyuc** [nctu16028/Exploring-Bezier-Curve#2]
I do not see code to sample on the curves.  I wonder how do you inspect the curves visually without sampling it?

**Comment by nctu16028** [comment]
I haven't done the visualization part yet. So far, I only print the coordinate of some points on the curve for checking correctness. (Line 20-28 of test.py) I think this part might be similar to what you mean "sampling".

**Comment by yungyuc** [comment]
Yes, https://github.com/nctu16028/Exploring-Bezier-Curve/blob/49006ffdf5a1892ce95d3a3bff76d3c41765d8a9/test.py#L20 is what I meant by sampling.

It will be much more productive for you to create a simple visualizer that samples the points.  Without the ability to _see_ it, coding for geometry is very convoluted.

I am closing the issue.  If you want to further discuss it, reopen it or open a new issue and tag me in it.
